Dockerize
stevenhay/DevOps-Course-Starter-Module-3 pull request #3
Opened 2021-01-04 18:10 UTC by stevenhay

docker

2021-01-15 09:42 UTC, JackMead requested changes
Nice work - this is a clean and effective docker container. I've left a few thoughts on what could be improved, but in particular
* The Readme should have full clear instructions for a new dev, including how to build those containers
* In the dev container, you should be able to reload any python file changes without having to rebuild the container - otherwise local development will be severely slowed!

2021-01-15 09:42 UTC, JackMead commented on README.md
> +Start the application on port 5000 using docker for development:
I think we're missing some preliminary instructions here; the user will need to have run a docker build command before they're able to run these containers

2021-01-15 09:42 UTC, JackMead commented on README.md
> +$ docker run --env-file ./.env.dev -p 5000:5000 todo-app:dev
This doesn't allow for hot reloading currently - if I make a change to one of the .py files I need to rebuild and run the new image. See the exercise notes on setting a bind mount to help with that

Also worth noting that here you assume a `.env.dev` file exists but there's no instructions anywhere warning a user they'll need to set one up

2021-01-15 09:42 UTC, JackMead commented on Dockerfile
> +RUN pip install poetry && poetry install --no-root --no-dev
Not important, but it would be nicer to install poetry through the officially recommended route rather than relying on pip here
(e.g. [see the official docs](https://python-poetry.org/docs/))

2021-01-15 09:42 UTC, JackMead commented on Dockerfile
> +ENV FLASK_ENV=development
Minor, but these will be overridden by the `.env` file if they're present there - could be worth making this clear somewhere as the `.env.template` file still contains that variable

2021-01-15 09:42 UTC, JackMead commented on .dockerignore
> +__pycache__
Nice, this ignore file looks pretty comprehensive

2021-01-22 09:35 UTC, stevenhay commented on README.md
> +Start the application on port 5000 using docker for development:
Added the build instructions :)

2021-01-22 09:35 UTC, stevenhay commented on README.md
> +$ docker run --env-file ./.env.dev -p 5000:5000 todo-app:dev
Added the bind mounts

2021-01-22 10:26 UTC, stevenhay commented on Dockerfile
> +ENV FLASK_ENV=development
done

2021-01-29 14:29 UTC, JackMead approved these changes
Thanks for updating the documentation, I'm happy to approve it now though there is one change that we should fix before merging that I've highlighted on the PR

2021-01-29 14:29 UTC, JackMead commented on README.md
> +$ docker build --target dev --mount type=bind,source=./todo_app,target=/app/todo_app --tag todo-app:dev .
We've slightly mixed up the build & run commands here, the `--mount type=...` argument will need to be passed as part of the run command, and you may find that you're unable to use the relative path syntax for `./todo_app` - that can be fixed by using the current working directory (e.g. with `source="$(pwd)"/todo_app`)

2021-02-04 09:47 UTC, merged